/**
 * Pull Fredoka and Nunito into the repo so the app owns its own fonts.
 *
 * Why this exists. The app used to load both faces from Google's CDN,
 * which is fine on a good connection and wrong everywhere else that
 * matters here:
 *
 *   - The offline shell precaches the whole app but cannot precache a
 *     cross-origin stylesheet, so the first offline launch fell back to
 *     system fonts and every heading changed shape.
 *   - The standalone single-file build embeds art and audio and then
 *     referenced nothing at all for type, so the file a parent saves and
 *     opens from a USB stick never looked like the game.
 *   - It is a third-party request made by a three-year-old's device on
 *     every cold load, and nothing about a rounded headline is worth that.
 *
 * Only the latin and latin-ext subsets are kept: the game's text is
 * English and the emoji come from the system, so cyrillic, greek, hebrew
 * and vietnamese would be about 60% of the bytes for none of the glyphs.
 *
 * Run manually when the font list changes:  node scripts/fetch-fonts.mjs
 * The output is committed, so a normal build never touches the network.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const outDir = join(root, 'public', 'fonts');
mkdirSync(outDir, { recursive: true });

const SRC = 'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@600;700;800;900&display=swap';
// Google serves a different stylesheet per user agent; this one gets woff2.
const UA = 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36';
const KEEP = new Set(['latin', 'latin-ext']);

const css = await fetch(SRC, { headers: { 'User-Agent': UA } }).then((r) => r.text());

// The stylesheet is a run of `/* subset */ @font-face { ... }` pairs.
const blocks = [...css.matchAll(/\/\*\s*([a-z-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)];
if (!blocks.length) throw new Error('[fonts] could not parse the stylesheet');

const out = [];
let kept = 0;
for (const [, subset, block] of blocks) {
  if (!KEEP.has(subset)) continue;
  const url = /url\((https:[^)]+)\)/.exec(block)?.[1];
  if (!url) continue;
  const name = url.split('/').pop();
  const bytes = Buffer.from(await fetch(url).then((r) => r.arrayBuffer()));
  writeFileSync(join(outDir, name), bytes);
  // Relative to THIS stylesheet, which already lives in fonts/ — writing
  // `./fonts/x.woff2` here resolves to fonts/fonts/x.woff2, and a dev
  // server's SPA fallback answers that with index.html and a 200, so the
  // browser reports no failed request and simply renders in the fallback
  // face. Nothing in the console, wrong type on screen.
  out.push(`/* ${subset} */\n${block.replace(url, `./${name}`)}`);
  kept += 1;
}

writeFileSync(
  join(outDir, 'fonts.css'),
  `/* Generated by scripts/fetch-fonts.mjs — do not edit by hand. */\n${out.join('\n')}\n`,
);
console.log(`[fonts] ${kept} faces kept of ${blocks.length}, written to public/fonts/`);
